name: Build Android APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APKs (sender & viewer)
        run: ./gradlew :android-sender:assembleDebug :android-viewer:assembleDebug

      - name: Upload Sender debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-sender-debug-apk
          path: android-sender/app/build/outputs/apk/debug/*.apk

      - name: Upload Viewer debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-viewer-debug-apk
          path: android-viewer/app/build/outputs/apk/debug/*.apk
